### ISSUE TITLE
ชื่อ package ผิดครับ

### ISSUE THREAD

**Issue by muay5157** [baraear/laravel-thailand-js#4]
`composer require baraear/laravel-thailand-js`

ต้องแก้เป็น

`composer require baraear/laravel-thailand`

**Comment by thanonoc** [comment]
@muay5157 ไม่ได้ผิดครับ ก่อนหน้าที่ผมทำโปรเจคแยกกันครับ มีทั้งแบบใช้ javascript และใช้ eloquent model ครับ
